//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeMii.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemeMii.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang7\ul\b\f0\fs22 Health Screen Tutorial\par
        ///\par
        ///\pard\sa200\sl276\slmult1\ulnone\b0 This is a simple tutorial for ThemeMii on how to make a custom health screen. It&apos;s very short and simple, but hopefully you will know how ThemeMii works when you&apos;re finished.\par
        ///First get yourself two custom health screen images:\par
        ///- The health screen itse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HealthTut {
            get {
                return ResourceManager.GetString("HealthTut", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ThemeMii_Icon {
            get {
                object obj = ResourceManager.GetObject("ThemeMii_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang7\ul\b\f0\fs22 ThemeMii Basic Instructions\par
        ///\par
        ///\pard\sa200\sl276\slmult1\b0\i mym Files:\ulnone\i0\par
        ///\par
        ///Basically, when we talk about themes, we&apos;re simply replacing original files, mostly images, but also other stuff like brlan&apos;s / brlyt&apos;s to change animations.\par
        ///Now, a mym file is actually a zip file containing the files to rep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThemeMiiBasics {
            get {
                return ResourceManager.GetString("ThemeMiiBasics", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ThemeMiiFull {
            get {
                object obj = ResourceManager.GetObject("ThemeMiiFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
